apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- aws-applicationset.yaml
- observability-applicationset.yaml
- testground-applicationset.yaml
- networking-applicationset.yaml
- testground-tools-applicationset.yaml
#- telegraf-operator.yaml
#- kustomization.yaml
#- influxdb.yaml
