apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- system-tools
- grafana
- grafana-agent-operator
- loki
- otel
- prometheus
- prometheus-crds
- promtail
- telegraf-operator
